version: "3.8"
networks:
    codo:
services:
  codo-admin:
    env_file:
      - ./env.sh
    restart: unless-stopped
    image: registry.cn-hangzhou.aliyuncs.com/sourcegarden/opendevops-admin:alpine-0.3.0
    volumes:
      - /var/log/supervisor/:/var/log/supervisor/
      - /sys/fs/cgroup:/sys/fs/cgroup
    ports:
      - "8010:80"
    networks:
      - codo